Repository Wanted-Pre-Onboarding-Frontend-2/wanted-pre-onboarding-fe-refactor, pull requests merged in 2022-07, with the labels that each got.

#2 refactor: 사용자 auth 로직을 선언적으로 수정
  .prettierrc
  src/components/base/Header.jsx
  src/components/member/LoginForm.jsx
  src/hooks/useAuth.jsx
  src/index.js
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/store/auth/provider.jsx
  src/store/auth/reducer.jsx
  src/util/checkIsVerifyAccount.jsx
Labels: refactor

#6 refactor: Image Lazy loading 구현
  src/assets/images/img_base.jpeg
  src/components/feed/Feed.jsx
  src/components/feed/LazyImg.jsx
  src/hooks/useLazyImageObserver.jsx
Labels: refactor

#10 refactor comment compoent 분리
  package-lock.json
  src/components/feed/Feed.jsx
  src/components/feed/comment/CommentList.jsx
  src/components/feed/comment/CommentWrite.jsx
Labels: refactor

#21 [#20] refactor: use the routes file to handle routing
  src/App.js
  src/components/member/LoginForm.jsx
  src/constants/routes.js
  src/index.js
  src/layout/AuthBtn.jsx
  src/layout/Header.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/routes/index.jsx
Labels: refactor

#17 [#16] refactor: add alt property, change lazy hook jsx -> js
  src/components/feed/LazyImg.jsx
  src/hooks/useLazyImageObserver.js
Labels: refactor

#19 [#13] feat add comment delete
  public/data/feedData.json
  src/components/feed/Feed.jsx
  src/components/feed/comment/CommentList.jsx
  src/components/feed/comment/CommentWrite.jsx
  src/styles/layout.scss
Labels: feat

#24 refactor: interactions, [add package]
  package-lock.json
  package.json
  src/components/feed/Feeds.jsx
  src/components/feed/LazyImg.jsx
  src/hooks/useThrottle.js
  src/layout/Header.jsx
  src/pages/Home.jsx
  src/styles/layout.scss
Labels: refactor, chore

#26 [#25] feat: Implement the user sign-up function
  src/hooks/useAuth.jsx
  src/store/auth/reducer.jsx
  src/util/checkAccount.js
  src/util/checkIsVerifyAccount.jsx
Labels: feat

#29 [#23] add like func
  src/components/feed/Feed.jsx
  src/components/feed/comment/CommentList.jsx
  src/components/feed/comment/CommentWrite.jsx
  src/styles/common.scss
Labels: feat, polish
